name: Result Job Parallelization 

on:
  # we want pull requests so we can build(test) but not push to image registry
  push:
    branches:
      - 'main'
      - result
    # only build when important files change
    paths:
      - 'result/**'
      - '.github/workflows/call-docker-build-result.yaml'
  pull_request:
    branches:
      - 'main'
    # only build when important files change
    paths:
      - 'result/**'
      - '.github/workflows/call-docker-build-result.yaml'
  # schedule:
  #   # re-run montly to keep image fesh with upstream base images
  #   - cron: '0 12 15 * *'

jobs:

  build-test-image:
    name: Building Image for testing
    runs-on: ubuntu-latest

    permissions:
      packages: write 

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setting up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to ghcr.io registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push to GHCR
        uses: docker/build-push-action@v6
        with:
          context: ./result
          push: true         
          tags: ghcr.io/wvrmhat/example-voting-app:${{ github.run_id }}
          cache-from: type=gha 
          cache-to: type=gha,mode=max
          platforms: linux/amd64


  test-unit:
    name: Unit tests
    needs: [build-test-image]
    runs-on: ubuntu-latest

    permissions:
      packages: read

    steps:

      - name: Login to ghcr.io registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Unit Testing in Docker
        run: docker run --rm ghcr.io/wvrmhat/example-voting-app:"$GITHUB_RUN_ID" echo "Run test commands here"

    
  test-integration:
    name: Integration testing in compose
    needs: [build-test-image]
    runs-on: ubuntu-latest

    permissions:
      packages: read

    steps:

      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to ghcr.io registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Executing Postgres healthcheck
      #   run: chmod +x ./healthchecks/postgres.sh 
      
      - name: Healthcheck in Docker Compose
        run: |
          export TESTING_IMAGE=ghcr.io/wvrmhat/example-voting-app:"$GITHUB_RUN_ID"
          # echo Testing image: "$TESTING_IMAGE"
          docker compose -f docker-compose.yml up --exit-code-from sut_result 


  test-k3d:
    name: Test deployment in Kubernetes
    needs: [build-test-image]
    runs-on: ubuntu-latest

    permissions:
      packages: read

    steps:

      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to ghcr.io registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}   


      - uses: AbsaOSS/k3d-action@v2
        with:
          cluster-name: "test-cluster-1"
          args: >-
            --agents 1
            --no-lb
            --k3s-arg "--no-deploy=traefik,servicelb,metrics-server@server:*"

      - name: Smoke test deployment in k3d Kubernetes
        run: |
          kubectl create secret docker-registry regcred \
          --docker-server=https://ghcr.io \
          --docker-username=${{ github.actor }} \
          --docker-password=${{ secrets.GITHUB_TOKEN }}
          export TESTING_IMAGE=ghcr.io/wvrmhat/example-voting-app:"$GITHUB_RUN_ID"
          envsubst < manifests/deployment.yaml  | kubectl apply -f -
          kubectl rollout status deployment myapp
          kubectl exec deploy/myapp -- curl --fail localhost:8888
        # for testing another time
        # envsubst < k8s-specifications/result-deployment.yaml | kubectl apply -f -
        # kubectl rollout status deployment result 
        # kubectl exec deploy/result --curl --fail localhost:80   
              
  cve-scanning:
    name: Scanning image with Trivy
    needs: [build-test-image]
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      security-events: write

    steps: 
      - name: Checkout git repo
        uses: actions/checkout@v4
            
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
                
      - name: Login to ghcr.io registry
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}      
            
      - name: Pull image to scan 
        run: docker pull ghcr.io/wvrmhat/example-voting-app:"$GITHUB_RUN_ID"

      - name: Running Trivvy for all CVEs (non-blocking)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/wvrmhat/example-voting-app:${{ github.run_id }}
          format: table
          exit-code: 0

  building-final-image:
      name: Build Final Image
      needs: [test-unit, test-integration, test-k3d, cve-scanning]
      runs-on: ubuntu-latest

      permissions:
        packages: write
        pull-requests: write 

      steps:

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
 
        - name: Login to ghcr.io registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Docker Metadata for Final Image Build
          id: docker_meta
          uses: docker/metadata-action@v5
          with:
            images: wvrmhat/example-voting-app,ghcr.io/wvrmhat/example-voting-app
            flavor: |
              latest=false
            tags: |
              type=raw,value=99

        - name: Docker Build and Push to GHCR and Docker Hub
          uses: docker/build-push-action@v6
          with: 
                push: true
                tags: ${{ steps.docker_meta.outputs.tags }}
                labels: ${{ steps.docker_meta.outputs.labels }}
                cache-from: type=gha
                cache-to: type=gha, mode=max
                platforms: linux/amd64,linux/arm64



  # call-docker-build:

  #   name: Call Docker Build

  #   uses: bretfisher/docker-build-workflow/.github/workflows/reusable-docker-build.yaml@main

  #   permissions:
  #     contents: read
  #     packages: write # needed to push docker image to ghcr.io
  #     pull-requests: write # needed to create and update comments in PRs
    
  #   secrets:

  #     # Only needed if with:dockerhub-enable is true below
  #     dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}

  #     # Only needed if with:dockerhub-enable is true below
  #     dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

  #   with:
      
  #     ### REQUIRED
  #     ### ENABLE ONE OR BOTH REGISTRIES
  #     ### tell docker where to push.
  #     ### NOTE if Docker Hub is set to true, you must set secrets above and also add account/repo/tags below
  #     dockerhub-enable: true
  #     ghcr-enable: true

  #     ### REQUIRED 
  #     ### A list of the account/repo names for docker build. List should match what's enabled above
  #     ### defaults to:
  #     image-names: |
  #       wvrmhat/examplevotingapp_result
  #       ghcr.io/wvrmhat/example-voting-app-result

  #     ### REQUIRED set rules for tagging images, based on special action syntax:
  #     ### https://github.com/docker/metadata-action#tags-input
  #     ### defaults to:
  #     # tag-rules: |
  #     #   type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
  #     #   type=ref,event=pr
  #     #   type=ref,event=branch
  #     #   type=semver,pattern={{version}}
  #     #   type=raw,value=gha-${{ github.run_id }}
      
  #     ### path to where docker should copy files into image
  #     ### defaults to root of repository (.)
  #     context: "{{defaultContext}}:result"
      
  #     ### Dockerfile alternate name. Default is Dockerfile (relative to context path)
  #     # file: Containerfile

  #     ### build stage to target, defaults to empty, which builds to last stage in Dockerfile
  #     # target:
      
  #     ### platforms to build for, defaults to linux/amd64
  #     ### other options: linux/amd64,linux/arm64,linux/arm/v7
  #     platforms: linux/amd64,linux/arm64,linux/arm/v7
      
  #     ### Create a PR comment with image tags and labels
  #     ### defaults to false
  #     # comment-enable: false
